### ISSUE TITLE
WIP: embessy version of adin1110 rust driver.

### ISSUE THREAD

**Issue by vDorst** [shulltronics/adin-1110-rs#1]
Hi,

I came a cross your repo.
I also working on a driver for the ADIN1110.

I do already have a working version for embassy embedded framework.
It is still a WIP but I do have a working http example see https://github.com/vDorst/embassy/tree/adin1110.
Goal is to finish this driver and make a PR for embassy.

**Comment by shulltronics** [comment]
Hi vDorst,

Thank you so much for sharing.. just today I was planning to start looking into how to add support for this chip to `embassy-net`! It looks like you already have a lot of good progress made! I will explore your code and try to get the example working and see what I might be able to add.

My original idea for this crate was to add support for a variety of frameworks behind feature flags, such as `embassy`, `smoltcp`, and `embedded-hal` v1; but perhaps keeping the embassy stuff in their repository makes sense.

Thanks again for showing me your work!

**Comment by vDorst** [comment]
I am closing this issue.
My work is merged so your can use embassy!
https://github.com/embassy-rs/embassy/tree/main/embassy-net-adin1110
